### ISSUE TITLE
Unable to Launch - NullPointerException

### ISSUE THREAD

**Issue by ScottoMotto** [Chocohead/Rift#26]
All of my previously working Rift 1.13.2 installs no longer work. Neither dynamic snapshots or hardcoded versions. Something with the mixin? All repos appear to be up.

MultiMC Crash Log
https://paste.ee/p/Lfu14

**Comment by Chocohead** [comment]
[That's](https://github.com/Chocohead/Rift/blob/jitpack/src/main/java/org/dimdev/riftloader/RiftLoader.java#L101) a very strange one. The only cases it would happen is if the OS forbid access to the mods folder for whatever reason, or there was a file called `mods` instead of it being a folder. Not a Mixin or mod thing at least I don't think.

**Comment by ScottoMotto** [comment]
Ha. you are right it was a strange one. I had the mods folder as a symlink doing some tests and removed the original. I never thought to look at that. So you nailed the reason. I'll close this in shame :)
