### ISSUE TITLE
Download problem, again.

### ISSUE THREAD

**Issue by MrMody0** [Chocohead/Rift#37]
Hi, problem with broken link exists again, i can't download and if i got file from another source - launcher still can't run becouse of this problem. What I have learned is the fact that the launcher is giving error: 
"Gave up trying to download https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar"
Link provides to site: 
"https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-2d8bb9bd56-/Rift-jitpack-2d8bb9bd56-.jar"
Which is not working of course, but if you add "1" after "-" in two spots - just before ".jar", and earlier before the "/", it's downloading. Can you fix it please? :D

_Originally posted by @MrMody0 in https://github.com/Chocohead/Rift/issues/35#issuecomment-488946645_

I am sorry for double posting, but i was not sure if anybody will see post #35.

**Comment by ItayZiv** [comment]
I managed to get it working by creating the exact path (.minecraft\libraries\com\github\Chocohead\Rift\jitpack-SNAPSHOT)
Then putting the jar in and renaming it to Rift-jitpack-SNAPSHOT.jar
(After downloading by adding 1 in the same spots you mentioned (https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-2d8bb9bd56-1/Rift-jitpack-2d8bb9bd56-1.jar)

**Comment by JinxLuckless** [comment]
I managed to download the file by adding 1 like @MrMody0 suggested. Then I created the exact path @epicDISZ suggested. I put the jar in the jitpack-SNAPSHOT folder, and renamed it.

I'm using MultiMC, so I then went to issue #7 and followed the instructions there & in the video.

I get this error:
"Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Shae Server, Luminex Edrien, Rift 1.13.2' failed to process:
https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-2d8bb9bd56-/Rift-jitpack-2d8bb9bd56-.jar"

I have tried renaming the folder & file to match that, including by adding or removing the 1 at the end, and I haven't had any luck. I get that exact same error no matter what I try. I also tried editing the json for MultiMC to change the name field to read, com.github.Chocohead:Rift:jitpack-2d8bb9bd56- but no such luck. I'm not sure what combination to try. There are so many variables.

Edit: SUCCESS! I needed to make the folder jitpack-2d8bb9bd56-1 and file same except for the Rift- in front, and then also change the json name field to com.github.Chocohead:Rift:jitpack-2d8bb9bd56-1

Phew!  :)  Hopefully that helps anyone who comes after me and can't get it working.

**Comment by MrMody0** [comment]
Well, we have 2 really great workarounds, but it should be fixed.. Big thanks guys <3

**Comment by epicDISZ** [comment]
@JinxLuckless I’m super unfamiliar with multimc but whatever that error seems like wherever that link is it’s missing the 2 1’s as @MrMody0 suggested, idk where that is, again super unfamiliar

**Comment by surekqomi** [comment]
Seems the link has now changed from -1 to -11. After that the above workarounds are still effective.
