### ISSUE TITLE
Rift 1.13.2 Fails to download on launcher

### ISSUE THREAD

**Issue by Paenthy** [Chocohead/Rift#43]
Game fails to launch with the following error:

""
Failed to download file. Rift-jitpack-SNAPSHOT.jar
Name: Rift-jitpack-SNAPSHOT.jar
URL: https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar
Error details: HTTP 404: 
Filename on disk: Rift-jitpack-SNAPSHOT.jar
Path: C:\Users\JF\AppData\Roaming\.minecraft\libraries\com\github\Chocohead\Rift\jitpack-SNAPSHOT\Rift-jitpack-SNAPSHOT.jar
Exists: false
 ""

Steps taken: 
- Fresh install of Minecraft;
- Fresh install of Java
- Fresh install of Rift
- With and without mods in folder

OS: Windows 10

**Comment by ghost** [comment]
I have same problem. :/ 
Hopefully that's gonna be fixed as soon.

**Comment by RadsammyT** [comment]
I think I know now.
When entering this link on a normal browser, which is a 404- would have this text when you click on that link.

> Tag or commit 'jitpack-d4cd7b00a-1' not found. Rechecking.

I would be sure that this is a result of a missing commit that would have been deleted in the pack.

**Comment by TheGnarp** [comment]
Yep, same thing here:

> Tag or commit 'jitpack-d4cd7b00a-1' not found. Rechecking.

Is there a workaround?

...

like...

- downloading the jar file from here:
   `https://jitpack.io/com/github/Chocohead/Rift/jitpack-d4cd7b00ba-1/Rift-jitpack-d4cd7b00ba-1.jar`
   `(d4cd7b00ba instead of d4cd7b00a)`

- installing it (after selecting 1.13.2 in the minecraft launcher),

- and also putting the same jar into
   `[your minecraft folder]\libraries\com\github\Chocohead\Rift\jitpack-SNAPSHOT\`

- but renaming it to
   `Rift-jitpack-SNAPSHOT.jar `

... maybe? ^_-

**Comment by dct0** [comment]
As per the instructions on the litematica and malilib mod page:

1. Install [this](https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-aeee80c1fb-1/Rift-jitpack-aeee80c1fb-1.jar) version of Rift.

2. Go to your `versions` folder in your minecraft directory, open the `1.13.2-rift-1.0.4-SNAPSHOT` folder

3. Open `1.13.2-rift-1.0.4-SNAPSHOT.json`

4. Change `SNAPSHOT` in the string `com.github.Chocohead:Rift:SNAPSHOT` found in the `libraries` array to `aeee80c1fb-1`, open the picture to check if you want

5. Save and launch

![Instructions in Image format for reference](https://i.imgur.com/6qAnDrV.png)
